bes: Convert JSON str to bytes for Python 3
Avoiding:

  ERROR: test_emit (test.test_bes.EmitTestCase)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/.../bes/test/test_bes.py", line 32, in test_emit
      payload={'hello': 'world', 'goodbye': 'everybody'})
    File "/.../bes/test/test_bes.py", line 25, in _call_emit
      *args, **kwargs)
    File "/.../bes/bes/__init__.py", line 119, in emit
      connection.send(message)
    File "/.../bes/bes/__init__.py", line 62, in send
      self._sock.sendto(message, (self.host, self.port))
  TypeError: 'str' does not support the buffer interface